-- require "eagle.keymaps-mine"
require "eagle.treesitter"
-- require("lz.n").load("eagle.lz-plugins")
-- require "eagle.telescope"
require "eagle.options"
-- require "eagle.colorscheme"
require "eagle.lsp-test"
require "eagle.cmp-test"
-- require "eagle.lualine-test"
-- require "eagle.toggleterm"
-- require "eagle.autopairs"
-- require "eagle.gitsigns"
require "eagle.autocommands-mine"
