require "eagle.options"
require "eagle.keymaps"
-- require "eagle.plugins"
require "eagle.colorscheme"
-- require "eagle.cmp"
-- require "eagle.lsp"
-- require "eagle.telescope"
-- require "eagle.gitsigns"
-- require "eagle.treesitter"
-- require "eagle.autopairs"
-- require "eagle.comment"
-- require "eagle.nvim-tree"
-- require "eagle.bufferline"
-- require "eagle.lualine"
-- require "eagle.toggleterm"
-- require "eagle.project"
-- require "eagle.impatient"
-- require "eagle.indentline"
-- require "eagle.alpha"
-- require "eagle.whichkey"
-- require "eagle.autocommands"
